# Generated by Django 4.2.6 on 2023-10-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_employeequeueassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='queue',
        ),
        migrations.AlterField(
            model_name='queue',
            name='state',
            field=models.CharField(choices=[('0', 'NEW'), ('1', 'IN_SERVICE'), ('2', 'DONE')], default='0', max_length=4),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
